[metadata]
package      = "mack"
version      = "1.0"
license      = "MIT"
section      = "utils"
priority     = "optional"
arch         = "x64_86"
vendor       = "midbel"
homepage     = "https://github.com/midbel/mack"
depends      = ["libc6"]
summary      = "Manage binary pACKage made easy."
description  = """mack help you to create your binary package without \
any external dependencies

Features:

* create deb package
* create rpm package
* show package information
"""
maintainer   = {
  name  = "midbel",
  email = "midbel@foobar.com",
}
compiler = "go-1.10"

[[control.changelog]]
date = 2018-05-15T12:10:00Z
maintainer = {
  name = "midbel",
  email = "midbel@foobar.com",
}
changes = """
- build deb package(s) from configuration file
- build rpm package(s) from configuration file
- merge rpm and deb command into one build command
"""


[[resource]]
source      = "bin/mack"
destination = "usr/bin/"
mode = 0755

[[resource]]
source = "src/github.com/midbel/mack/LICENSE"
destination = "usr/share/doc/mack/"
filename = "copyright"

# [[resource]]
# source      = "src/github.com/midbel/mack/doc/CHANGELOG"
# destination = "usr/share/doc/mack/"
# filename    = "changelog.Debian.gz"
# compress    = true

# [[resource]]
# source      = "src/github.com/midbel/mack/doc/mack.1"
# destination = "usr/share/man/man1"
# compress    = true
# filename    = "mack.1.gz"

[[resource]]
source      = "src/github.com/midbel/mack/examples/mack.toml"
destination = "usr/share/doc/mack/examples/mack.toml"
